import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import React from 'react'
import { Navbar, Nav } from 'react-bootstrap'
import Link from 'next/Link'
export default function AddPerson()
{
return (
    <div className={styles.container}>
<Head>
<title>Welcome to Social Stars!</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
<p>The Add Person page is currently under construction. Check back soon!</p>
</div>
)}