import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/Link'
import { Navbar, Nav } from 'react-bootstrap'
import NavBar from './NavBar'
export default function HomePage()
{
    return(
<div className={styles.container}>
<Head>
<title>Welcome to Social Stars!</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
<p>The Inbox page is currently under construction. Check back soon!</p>
<Link legacyBehavior href="/"> 
        <a className="btn btn-success">Home</a>
        </Link>
</div>
    )
}