import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import React from 'react'
import { Navbar, Nav } from 'react-bootstrap'
import Link from 'next/Link'
export default function Input()
{
    {
        const api_url ="https://ciprand.p3p.repl.co/api?len=20&count=10";
        async function getNewStatus(url)
        {
          const response = await fetch(url);
          var data = await response.json();
          console.log(data);
            return data;
           
        }
        getNewStatus(api_url);
    }
    
    return ( 
        <div className={styles.container}>
            <Head>
                <title>Social Stars</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Input
                </h1>
                <p className={styles.description}>
                    Enter your status update below
                </p>

            </main>
        </div>
    )
}
