import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import React from 'react'
import { Navbar, Nav } from 'react-bootstrap'
import Link from 'next/Link'
export default function Search()
{
    //search for other people online
    const handleSubmit = async (e) => {
        e.preventDefault()
        const res = await fetch('https://random-data-api.com/api/v2/', {
            body: JSON.stringify({
                status: e.target.status.value,
            }),
            headers: {
                'Content-Type': 'application/json'
            },
            method: 'POST'
        })
        const result = await res.json()
        e.target.reset()
    }
    async function getRandomUsers() {
        try {
          const data = await axios.get("/api/users/random_user?size=3");
          return data;
        } catch(err) {
          console.log("error: ", err);
        }
      }
return (
    <div className={styles.container}>
<Head>
<title>Welcome to Social Stars!</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head>
<h1>Search for other people online</h1>
            <form onSubmit={handleSubmit}>
                <label htmlFor="search">Search</label>
                <input id="search" name="search" type="text" />
                <button>Submit</button>
            </form>
<Link legacyBehavior href="/"> 
        <a className="btn btn-success">Home</a>
        </Link>
</div>
)}